### ISSUE TITLE
Can not initialize ModelicaSystem with a stand alone modell

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OMPython#157]
```.mo
model foobar
parameter Real x = 1.0;
Real y;
equation
  y = 0.5*x;
  
end foobar;
```

and trying to instantiate ``` ModelicaSystem ``` class with it 

```.py
from OMPython import ModelicaSystem

mo = ModelicaSystem("C:/~/foobar.mo", "foobar")

```

resulting in attribute error

```
Traceback (most recent call last):

  File "C:\Users\~\AppData\Local\Temp/ipykernel_13720/1490029352.py", line 1, in <module>
    mo = ModelicaSystem("C:/Users/~/Documents/foobar.mo", "foobar")

  File "d:\~\lib\site-packages\OMPython\__init__.py", line 867, in __init__
    self.__loadingModel()

  File "d:\~\lib\site-packages\OMPython\__init__.py", line 907, in __loadingModel
    self.buildModel()

  File "d:\~\lib\site-packages\OMPython\__init__.py", line 917, in buildModel
    self.xmlparse()

  File "d:\~\lib\site-packages\OMPython\__init__.py", line 962, in xmlparse
    ch = sv.getchildren()

AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by Arinomo** [comment]
Re-Install OMPython from Github instead of automatically download/install using pip.

Source code in PyPi.org is still using 
```.py
ch = sv.getchildren()
```

and the one on Github [L973](https://github.com/OpenModelica/OMPython/blob/master/OMPython/__init__.py#L973) is using

```.py
ch = list(sv)
```
